version: "2"

services:
  app:
    container_name: app
    build: .
    restart: unless-stopped
    env_file: .env
    environment:
      - ENV
      - HTTP_PORT
      - JWT_SECRET
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB_NAME
      - MONGO_USERNAME
      - MONGO_PASSWORD
      - MONGO_DEBUG
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    networks:
      - app-network
  mongo:
    container_name: mongo
    image: mongo:4.2
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - dbdata:/data/db
    networks:
      - app-network
    ports:
      - "${MONGO_PORT}:27017"

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  node_modules:
