version: "3"

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
  node-modules:

services:
  app:
    build: .
    command: "${DOCKER_COMMAND}"
    restart: unless-stopped
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    networks:
      - app-network
    volumes:
      - .:/usr/src/app
      - node-modules:/usr/src/app/node_modules
    environment:
      - MONGO_HOST=mongo
  mongo:
    image: mongo:4.2
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:27017"
    networks:
      - app-network
    volumes:
      - db-data:/data/db
